name: Deploy Frontend to Vercel

on:
  push:
    branches: [ main ]
    paths:
      - 'FE/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v41.1.4
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}  # Tùy chọn: Để comment URL deploy lên GitHub
          vercel-args: '--prod'  # Tùy chọn: Deploy production